# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 11:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Title')),
                ('duration', models.CharField(default='00:00', max_length=100, verbose_name='Duration')),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('text', models.TextField(blank=True, default=None, null=True, verbose_name='Text')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
