# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170203_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_korean',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='file',
            field=models.FileField(default=None, upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='record',
            name='filename',
            field=models.CharField(default=None, max_length=255, verbose_name='Filename'),
        ),
    ]
